routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products', ProductController::class);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'price',
        'description',
        'featured_image',
    ];

    public function images()
    {
        return $this->hasMany(ProductImage::class);
    }

    public function featuredImage()
    {
        return $this->belongsTo(ProductImage::class, 'featured_image');
    }
}

app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductImage extends Model
{
    use HasFactory;

    protected $fillable = [
        'product_id',
        'path'
    ];

    protected $appends = ['src'];

    public function images()
    {
        return $this->hasMany(ProductImage::class, 'featured_image');
    }

    /**
     * Get user profile picture
     *
     * returns string (full image path)
     */
    public function getSrcAttribute()
    {
        return url(config('file.product_images_path') . $this->path);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Events\NewProductAddedEvent;
use App\Exceptions\ProductImageException;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Services\ProductImageService;
use Exception;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{

    /**
     * @var ProductImageService
     */
    private $productImageService;

    public function __construct(ProductImageService $productImageService) 
    {
        $this->productImageService = $productImageService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $products = Product::with(['images', 'featuredImage'])->get();
        } catch(Exception $e) {
            return redirect()->back()->with(['error' => 'feching data faild']); 
        }
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(productRequest $request)
    {
        try {
            $product = Product::create([
                'name' => $request->name,
                'description' => $request->description,
                'price' => $request->price,
            ]);
    
            $this->updateProductImages($request, $product);
            
        } catch(ProductImageException $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        };

        $product->featuredImage;
        $product->images;

        $data = [
            'mail' => 'owner@product.com',
            'name' => $product->name,
            'price' => $product->price,
            'description' => $product->description,
            'mailFrom' => config('mail.from.address'),
            'mailName' => config('mail.from.name'),
            'mailTitle' => 'New Product Added',
        ];

        event(new NewProductAddedEvent($data));

        return response()->json([
            'message' => 'Successfully add product',
            'product' => $product
        ], 200);
    }
    /**
     * Update product images
     * @param Request $request
     * @param Product $product
     */
    public function updateProductImages($request, $product)
    {
        // create featured image
        $imageName = $this->productImageService->moveImage($request->featuredImage);
        $productImage = $this->productImageService->createProductImge($product->id, $imageName);
        $product->featured_image = $productImage->id;
        $product->save();

        // create product images
        if($request->has('productImages')) {
            foreach($request->productImages as $productImage) {
                $imageName = $this->productImageService->moveImage($productImage);
                $this->productImageService->createProductImge($product->id, $imageName);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(productRequest $request, Product $product)
    {
        $product->update([
            'name' => $request->name,
            'description' => $request->description,
            'price' => $request->price,
        ]);

        $this->removeProductImages($product);

        $this->updateProductImages($request, $product);

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->removeProductImages($product);
        $product->delete();
        Session::flash('success', 'Successfully delete');
        return redirect()->route('products.index');
    }

    public function removeProductImages($product)
    {
        $productImages = $product->images;
        foreach($productImages as $productImage) {
            File::delete(config('file.product_images_dir') . $productImage->path);
        }
    }
}

resources/views/product/add.blade.php
<!-- Modal -->
<div id="addModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title">Add Product</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form id="addProductForm" class="row mx-2" action="{{route('products.store')}}" method="POST" style="width: 470px" enctype="multipart/form-data">
            @csrf
            <div class="col-12 pt-4">
              <h4 class="pb-3 primary-color font-400">Product Name</h4>
              <input type="text" class="form-control @error('name') is-invalid @enderror" placeholder="Product Name" name="name" value="{{old('name') ?? ''}}">
                @error('name')
                    <span class="invalid-feedback d-block" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="col-12 pt-4">
              <h4 class="pb-3 primary-color font-400">Price</h4>
              <input type="number" step="0.01" class="form-control @error('price') is-invalid @enderror" placeholder="Price" value="{{old('price') ?? ''}}" name="price">
                @error('price')
                    <span class="invalid-feedback d-block" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="col-12 pt-4">
              <h4 class="pb-3 primary-color font-400">Description</h4>
              <textarea class="form-control @error('description') is-invalid @enderror" placeholder="Product Name" name="description">{{old('description') ?? ''}}</textarea>
                @error('description')
                    <span class="invalid-feedback d-block" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="col-12 pt-4">
                <h4 class="pb-3 primary-color font-400">Featured Image</h4>
                <input type="file" class="form-control @error('featuredImage') is-invalid @enderror" name="featuredImage">
                @error('featuredImage')
                    <span class="invalid-feedback d-block" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="col-12 pt-4">
                <h4 class="pb-3 primary-color font-400">Product Images</h4>
                <input type="file" class="form-control" name="productImages[]" multiple>
            </div>
            <div class="col-12 pt-4">
                <button type="submit" class="btn btn-success">Add</button>
            </div>

        </form> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default close-add-form">Close</button>
      </div>
    </div>

  </div>
</div>

resources/views/product/card.blade.php
<div class="" id="mock-card" style="display: none">
  <div class="grid col-4 mb-5">
    <div class="grid__item">
        <div class="card"><img class="card__img" src="+FEATURED_IMAGE+" alt="Desert">
            <div class="card__content">
                <h1 class="card__header">+NAME+</h1>
                <p class="card__text" style="min-height: 150px">
                    +DESCRIPTION+
                </p>
                <div class="mb-3">
                    <h1>All Product Images</h1>
                    +PRODUCT_IMAGES+
                </div>
                <div class="d-flex" style="justify-content: space-between">
                    <a href="{{route('products.edit', '+PRODUCT_ID+')}}" style="text-decoration: none">
                        <button class="card__btn">
                            EDIT<span>&rarr;</span>
                        </button>
                    </a>  
                    <form action="{{route('products.destroy', '+PRODUCT_ID+')}}" method="POST">
                      @csrf
                      @method('delete')
                      <button type="submit" class="card__btn">DELETE 
                          <span>&rarr;</span>
                      </button>
                  </form>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>